// <auto-generated />
using System;
using System.Collections.Generic;
using Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Core.Domain.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ScheduledJobId")
                        .HasColumnType("text")
                        .HasColumnName("scheduled_job_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agent_runs");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_agent_runs_brand_id");

                    b.ToTable("agent_runs");
                });

            modelBuilder.Entity("Backend.Core.Domain.ApprovalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("EditedCaption")
                        .HasColumnType("text")
                        .HasColumnName("edited_caption");

                    b.PrimitiveCollection<List<string>>("EditedHashtags")
                        .HasColumnType("text[]")
                        .HasColumnName("edited_hashtags");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RegenerateMode")
                        .HasColumnType("text")
                        .HasColumnName("regenerate_mode");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.HasKey("Id")
                        .HasName("pk_approval_actions");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_approval_actions_brand_id");

                    b.ToTable("approval_actions");
                });

            modelBuilder.Entity("Backend.Core.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_assets_brand_id");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("Backend.Core.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.ToTable("brands");
                });

            modelBuilder.Entity("Backend.Core.Domain.BrandMetaConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FacebookPageId")
                        .HasColumnType("text")
                        .HasColumnName("facebook_page_id");

                    b.Property<string>("IgBusinessAccountId")
                        .HasColumnType("text")
                        .HasColumnName("ig_business_account_id");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenCiphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_ciphertext");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_type");

                    b.HasKey("Id")
                        .HasName("pk_brand_meta_connections");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_brand_meta_connections_brand_id");

                    b.ToTable("brand_meta_connections");
                });

            modelBuilder.Entity("Backend.Core.Domain.BrandProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("AudiencePainPoints")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("audience_pain_points");

                    b.PrimitiveCollection<List<string>>("AudienceSegments")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("audience_segments");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.PrimitiveCollection<List<string>>("ColorHexes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("color_hexes");

                    b.PrimitiveCollection<List<string>>("ContentPillars")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("content_pillars");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageryStyle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imagery_style");

                    b.Property<string>("Positioning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("positioning");

                    b.Property<string>("ProductContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_context");

                    b.PrimitiveCollection<List<string>>("ToneDescriptors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tone_descriptors");

                    b.PrimitiveCollection<List<string>>("VoiceDo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("voice_do");

                    b.PrimitiveCollection<List<string>>("VoiceDont")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("voice_dont");

                    b.HasKey("Id")
                        .HasName("pk_brand_profiles");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_brand_profiles_brand_id");

                    b.ToTable("brand_profiles");
                });

            modelBuilder.Entity("Backend.Core.Domain.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_content_items");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_content_items_brand_id");

                    b.ToTable("content_items");
                });

            modelBuilder.Entity("Backend.Core.Domain.EvalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_eval_records");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_eval_records_brand_id");

                    b.ToTable("eval_records");
                });

            modelBuilder.Entity("Backend.Core.Domain.EvalResultRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_id");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_usd");

                    b.Property<string>("EvaluatorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evaluator_name");

                    b.Property<long?>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_eval_results");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_eval_results_brand_id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_eval_results_run_id");

                    b.ToTable("eval_results");
                });

            modelBuilder.Entity("Backend.Core.Domain.EvalRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aggregates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("aggregates");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataset_name");

                    b.Property<int>("DatasetSize")
                        .HasColumnType("integer")
                        .HasColumnName("dataset_size");

                    b.Property<string>("DatasetVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataset_version");

                    b.Property<string>("GitSha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("git_sha");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.HasKey("Id")
                        .HasName("pk_eval_runs");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_eval_runs_brand_id");

                    b.ToTable("eval_runs");
                });

            modelBuilder.Entity("Backend.Core.Domain.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("doc_type");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("Facet")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("facet");

                    b.Property<Guid>("KnowledgeDocId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_doc_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_chunks");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_knowledge_chunks_brand_id");

                    b.ToTable("knowledge_chunks");
                });

            modelBuilder.Entity("Backend.Core.Domain.KnowledgeDoc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("doc_type");

                    b.Property<string>("Facet")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("facet");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_docs");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_knowledge_docs_brand_id");

                    b.ToTable("knowledge_docs");
                });

            modelBuilder.Entity("Backend.Core.Domain.PublishRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<string>("CreationId")
                        .HasColumnType("text")
                        .HasColumnName("creation_id");

                    b.Property<string>("EngagementKeys")
                        .HasColumnType("jsonb")
                        .HasColumnName("engagement_keys");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text")
                        .HasColumnName("external_ref");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_publish_records");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_publish_records_brand_id");

                    b.HasIndex("ContentItemId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ix_publish_records_content_item_id_channel");

                    b.ToTable("publish_records");
                });

            modelBuilder.Entity("Backend.Core.Domain.RunCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state_json");

                    b.HasKey("Id")
                        .HasName("pk_run_checkpoints");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_run_checkpoints_brand_id");

                    b.ToTable("run_checkpoints");
                });

            modelBuilder.Entity("Backend.Core.Domain.EvalResultRow", b =>
                {
                    b.HasOne("Backend.Core.Domain.EvalRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eval_results_eval_runs_run_id");
                });
#pragma warning restore 612, 618
        }
    }
}
